<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro" />

    <!-- CHASSIS  CONF-->
    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.5"/>
    
    <!--  ROUES CONF -->
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.09"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    
    <!-- POSITIONS DES ROUES  -->
    <xacro:property name="wheel_offset_x_front" value="0.120"/>
    <xacro:property name="wheel_offset_x_rear" value="-0.120"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>

    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    
    <link name="base_link">
    </link>

    
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

   
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- MACRO POUR CRÉER UNE ROUE -->
    <xacro:macro name="wheel" params="prefix x_pos y_pos">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${x_pos} ${y_pos} 0" rpy="${-pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    
    <!-- Roues avant -->
    <xacro:wheel prefix="front_left" x_pos="${wheel_offset_x_front}" y_pos="${wheel_offset_y}"/>
    <xacro:wheel prefix="front_right" x_pos="${wheel_offset_x_front}" y_pos="${-wheel_offset_y}"/>
    
    <!-- Roues arrière -->
    <xacro:wheel prefix="rear_left" x_pos="${wheel_offset_x_rear}" y_pos="${wheel_offset_y}"/>
    <xacro:wheel prefix="rear_right" x_pos="${wheel_offset_x_rear}" y_pos="${-wheel_offset_y}"/>

</robot>